name: Compliance_Checking
on:
  pull_request:
    paths:    
      - '**.cls'
      - '!unpackaged/**.cls'
jobs:
  CoreLoggingCompliance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            ref: ${{ github.event.pull_request.head.ref }}
      - name: Check for References to SfdoLogging
        id: diff
        env:
          BASE_BRANCH: ${{ github.base_ref }}
          PR_BRANCH: ${{ github.event.pull_request.head.ref }}
        run: |
          if [ $GITHUB_BASE_REF ]; then
            # Pull Request
          git fetch origin $GITHUB_BASE_REF:$GITHUB_BASE_REF --depth=1
            echo "RUN: git diff-tree $GITHUB_BASE_REF..$PR_BRANCH --patch-with-raw"
            export DIFF=$( git diff-tree $GITHUB_BASE_REF..$PR_BRANCH --patch-with-raw | grep 'SfdoLogUtils.log' )
            echo "Diff between origin/$GITHUB_BASE_REF and $GITHUB_SHA"
          fi
          echo "$DIFF"
          # Escape newlines (replace \n with %0A)
          echo "::set-output name=diff::$( echo "$DIFF" | sed ':a;N;$!ba;s/\n/%0A/g' )"
      - run: echo "${{ steps.diff.outputs.diff }}"
